services:
  tg-ws-proxy:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: tg-ws-proxy
    restart: always

    ports:
      - "1443:1443/tcp"

    environment:
      TG_WS_PROXY_SECRET: "${TG_WS_PROXY_SECRET:?TG_WS_PROXY_SECRET is required}"
