services:
  tg-ws-proxy:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: tg-ws-proxy
    restart: always

    ports:
      - "1443:1443/tcp"

    environment:
      TG_WS_PROXY_HOST: "0.0.0.0"
      TG_WS_PROXY_PORT: "1443"
      TG_WS_PROXY_SECRET: "${TG_WS_PROXY_SECRET:?TG_WS_PROXY_SECRET is required}"
      TG_WS_PROXY_DC_IPS: "2:149.154.167.220 4:149.154.167.220"
      TG_WS_PROXY_CF_WORKER: ""
